language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
notifications:
  email:
    recipients:
      - ronapelbaum@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
